Require naminator

Output demo.gif

Set Shell "zsh"
Set FontSize 20
Set Width 1500
Set Height 1200
Set Theme "tokyonight"
Set FontFamily "Hack Nerd Font"

Hide
Type "setopt interactivecomments" Enter
Type "alias ls='exa --group-directories-first'" Enter
Type "clear" Enter
Show

Sleep 1s
Type "ls -T ./photo" Sleep 0.2s Enter Sleep 0.5s
Sleep 2s
Type "naminator -tec ./photo/10550129" Sleep 0.2s Enter Sleep 0.5s
Sleep 1s
Type "ls -T ./photo" Sleep 0.2s Enter Sleep 0.5s
Sleep 3s
